[package]
name = "hell_renderer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hell_core      = { path = "../hell_core" }
hell_common    = { path = "../hell_common" }
hell_error     = { path = "../../../hust/crates/hell_error" }
hell_utils     = { path = "../hell_utils" }
hell_resources = { path = "../hell_resources" }

num = "0.4.0"
glam = "0.21.3"
ash = "0.37.0+1.3.209"
memoffset = "0.6.5"
image  = "0.24.3"
lazy_static = "1.4"
