[package]
name = "shader_crap"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
hell_error.workspace = true
hell_collections.workspace = true

glam.workspace = true

num.workspace = true
num-traits.workspace = true
num-derive.workspace = true

pest = "2.5.3"
pest_derive = "2.5.3"
