[package]
name = "hell_renderer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hell_utils = { path = "../hell_utils" }

ash = "0.37.0+1.3.209"
